name: Build and Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - production  # change if your branch is 'desktop-development'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Notal-app"  # your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish
